version: "3"

services:
  server:
    environment:
      - REDIS_CONTAINER=redis:6379
      - LISTEN_PORT=:8010
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - ./group:/var/lib/redis
